# Generated by Django 5.1.4 on 2024-12-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_clients_contact_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='image',
            field=models.ImageField(null=True, upload_to='media/services'),
        ),
    ]
